name: Django check project

on:
  push:
    branches: [ master ]


jobs:
  validate:
    name: Validate django project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: action/setup-python@v6
        with:
          python-version: '3.13'
     
      - name: Create venv and install libs
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check django settings
        run: |
          source .venv/bin/activate
          echo "Проверка настроек Django"
          python3 manage.py check
          echo "Настройки валидны"
      
      - name: Check djando migrations
        run: |
          source .venv/bin/activate
          echo "Проверка миграций Django"
          python3 manage.py makemigrations --check --dry-run
          echo "Миграции валидны"

  test:
    name: Test django project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: action/setup-python@v6
        with:
          python-version: '3.13'
     
      - name: Create venv and install libs
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check djando staticfiles
        run: |
          source .venv/bin/activate
          echo "Проверка статик-файлов Django"
          python3 manage.py collectstatic --noinput --dry-run
          echo "Статики валидны"
